name = "tgbot"
main = "src/index.js"
compatibility_date = "2026-04-14"

[vars]
# Update region labels and Telegram group links before deploy.
REGION_1_NAME = "China Mainland"
REGION_2_NAME = "Europe"
REGION_3_NAME = "Japan"
REGION_4_NAME = "Latin America"
REGION_5_NAME = "South Korea"
REGION_6_NAME = "southeast Asia"
REGION_7_NAME = "Taiwan"
REGION_8_NAME = "USA and CA"

REGION_1_URL = "https://t.me/+Qj7MHJhndD85YzQy"
REGION_2_URL = "https://t.me/+mTNAsyrEP_c2MDdi"
REGION_3_URL = "https://t.me/+B5Efry8qozdlNWM6"
REGION_4_URL = "https://t.me/+W-SgzDKjsKMwOGRi"
REGION_5_URL = "https://t.me/+KThzdu8nguU2OWEy"
REGION_6_URL = "https://t.me/+Zm1y8pCEyV9lMjNi"
REGION_7_URL = "https://t.me/+aB4Rh8J0LsdlYTk6"
REGION_8_URL = "https://t.me/+14tEhSTJ0agyYmEy"
